export const DB_PATHS = {
  USERS: "users",
  USERNAMES: "usernames",
  BOXES: "boxes",
  ORDERS: "orders",
  ADDRESSES: "addresses",
  MESSAGES: "messages",
  CONVERSATIONS: "conversations",
  NOTIFICATIONS: "notifications",
  REPORTS: "reports",
  COMMENTS: "comments",
  CATEGORIES: "categories",
  SELLER_REQUESTS: "seller_requests",
  VERIFICATION_REQUESTS: "verification_requests",
  ADMIN_MESSAGES: "admin_messages",
  DONATIONS: "donations",
  FOLLOWS: "follows",
  FOLLOWERS: "followers",
  RECOVERY_CODES: "recovery_codes",
  EMERGENCY_CODES: "emergency_codes",
  RECOVERY_REQUESTS: "recovery_requests",
  PLATFORM_SETTINGS: "platform_settings",
} as const

export const FIREBASE_CONFIG = {
  apiKey: process.env.NEXT_PUBLIC_FIREBASE_API_KEY,
  authDomain: process.env.NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN,
  databaseURL: process.env.NEXT_PUBLIC_FIREBASE_DATABASE_URL,
  projectId: process.env.NEXT_PUBLIC_FIREBASE_PROJECT_ID,
  storageBucket: process.env.NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET,
  messagingSenderId: process.env.NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID,
  appId: process.env.NEXT_PUBLIC_FIREBASE_APP_ID,
}
